# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-Only-1.0

images:
  tags:
    init: docker.io/omecproject/pod-init:1.0.0
    bess: docker.io/omecproject/upf-epc-bess:master-latest
    cpiface: docker.io/omecproject/upf-epc-cpiface:master-latest
  pullPolicy: Always

nodeSelectors:
  enabled: false
  spgwu:
    label: omec-upf
    value: enabled

resources:
  enabled: true
  bess:
    requests:
      cpu: 2
      memory: 256Mi
    limits:
      cpu: 2
      memory: 256Mi
  routectl:
    requests:
      cpu: 256m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 128Mi
  web:
    requests:
      cpu: 256m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 128Mi
  cpiface:
    requests:
      cpu: 256m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 128Mi

config:
  coreDump:
    enabled: false
    path: /tmp/coredump
  spgwu:
    hugepage:
      enabled: true
    sriov:
      enabled: true
    # Provide UPF interface driver.
    # Available options are dpdk, af_xdp, af_packet.
    mode: "dpdk"
    name: "dp-name"
    workers: 1
    maxSessions: 50000
    # Provide the S1U and SGI networks facing device name and IP address
    s1u:
      device: s1u
      subnet: 192.168.252.0/24
      gateway: 192.168.252.1
      ip: 192.168.252.3
    sgi:
      device: sgi
      subnet: 192.168.250.0/24
      gateway: 192.168.250.1
      ip: 192.168.250.3
    enb:
      subnet: 192.168.251.0/24
    ue:
      subnet: 10.250.0.0/16
    zmq:
      recvPort: 20
      spgwc:
        addr: spgwc-headless
        port: 21
    bess:
      web:
        nodePort: 36000
    # Dynamic IP allocation is not supported for the user plane interfaces
    ipam: static
    cniPlugin: vfioveth
    hugepage:
      enabled: true
    sriov:
      enabled: true
